---
title: "Homework 6"
author: "Eman Ibrahim"
output: github_document
    
---


```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(rvest)
library(lme4)
library(modelr)
library(mgcv)
library(broom.mixed)
library(purrr)
library(broom)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1
Loading the homicide dataset then cleaning it
```{r}
homicides = 
  read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")

clean_df =
  homicides |>
  mutate(
    city_state = str_c(city, ", ", state),        
    solved = if_else(disposition == "Closed by arrest", 1, 0),
    victim_age = as.numeric(victim_age)
  ) |>
  filter(
    !(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL")),
    victim_race %in% c("White", "Black")
  )
```
Baltimore only logistic regression:
```{r}
baltimore_df =
  clean_df |>
  filter(city_state == "Baltimore, MD")

baltimore_model =
  glm(
    solved ~ victim_age + victim_sex + victim_race,
    data = baltimore_df,
    family = binomial()
  )
```


Let's get the adjusted OR and 95% CI for male vs female:
```{r}
baltimore_results=
  baltimore_model |> 
  tidy(conf.int = TRUE, exponentiate=TRUE)

baltimore_results |> 
  filter(term == "victim_sexMale") |> 
  select(term, estimate, conf.low, conf.high)
```





















